import type { ExpectedGameLogEntry } from '../helpers/game-log-oracle';

export const expectedGameLog = [
  ['game/created', 'Asha opened the bazaar'],
  ['player/joined', 'Belen joined the bazaar'],
  ['player/ready', 'Asha is ready'],
  ['player/ready', 'Belen is ready'],
  ['round/started', 'Asha opened round 1 · Asha starts'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/taken-camels', 'Belen took all 3 camels'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/taken-one', 'Asha took Diamond'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/taken-one', 'Belen took Gold'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/sold', 'Belen sold 2 Gold · earned 2 tokens'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/taken-camels', 'Asha took all 1 camel'],
  ['cards/taken-one', 'Belen took Diamond'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/sold', 'Belen sold 2 Diamond · earned 2 tokens'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/taken-one', 'Belen took Diamond'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Belen took Spice'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/sold', 'Belen sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Belen took Diamond'],
  ['cards/taken-one', 'Asha took Silver'],
  ['cards/sold', 'Belen sold 2 Diamond · earned 2 tokens'],
  ['cards/sold', 'Asha sold 2 Silver · earned 2 tokens'],
  ['cards/taken-one', 'Belen took Silver'],
  ['cards/taken-camels', 'Asha took all 1 camel'],
  ['cards/sold', 'Belen sold 2 Silver · earned 2 tokens'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Asha took Diamond'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/sold', 'Asha sold 2 Diamond · earned 1 token'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/taken-one', 'Belen took Spice'],
  ['cards/taken-camels', 'Asha took all 1 camel'],
  ['cards/sold', 'Belen sold 1 Spice · earned 1 token'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Belen took Silver'],
  ['cards/taken-one', 'Asha took Gold'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/taken-one', 'Belen took Spice'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Spice · earned 1 token · Belen won round 1'],
  ['round/started', 'Asha opened round 2 · Asha starts'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Belen sold 2 Silver · earned 2 tokens'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/taken-camels', 'Asha took all 3 camels'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/taken-one', 'Belen took Spice'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Spice · earned 1 token'],
  ['cards/taken-one', 'Asha took Diamond'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/sold', 'Asha sold 2 Diamond · earned 2 tokens'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Belen took Gold'],
  ['cards/taken-camels', 'Asha took all 1 camel'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/taken-one', 'Belen took Gold'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Belen sold 2 Gold · earned 2 tokens'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/taken-one', 'Belen took Spice'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Spice · earned 1 token'],
  ['cards/taken-one', 'Asha took Gold'],
  ['cards/taken-one', 'Belen took Gold'],
  ['cards/taken-one', 'Asha took Gold'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/sold', 'Asha sold 2 Gold · earned 2 tokens'],
  ['cards/taken-one', 'Belen took Diamond'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/sold', 'Belen sold 2 Diamond · earned 2 tokens'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Belen took Spice'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/sold', 'Belen sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/taken-one', 'Belen took Diamond'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Belen took Silver'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/taken-one', 'Belen took Silver'],
  ['cards/taken-camels', 'Asha took all 1 camel'],
  ['cards/sold', 'Belen sold 2 Silver · earned 2 tokens'],
  ['cards/taken-one', 'Asha took Silver'],
  ['cards/taken-one', 'Belen took Diamond'],
  ['cards/sold', 'Asha sold 2 Silver · earned 1 token · Asha won round 2'],
  ['round/started', 'Asha opened round 3 · Belen starts'],
  ['cards/sold', 'Belen sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Asha sold 2 Diamond · earned 2 tokens'],
  ['cards/sold', 'Belen sold 3 Gold · earned 4 tokens'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/taken-camels', 'Belen took all 3 camels'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/taken-camels', 'Belen took all 2 camels'],
  ['cards/taken-one', 'Asha took Diamond'],
  ['cards/taken-one', 'Belen took Diamond'],
  ['cards/taken-camels', 'Asha took all 1 camel'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/taken-one', 'Belen took Gold'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/taken-one', 'Asha took Diamond'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/sold', 'Asha sold 2 Diamond · earned 2 tokens'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/taken-camels', 'Asha took all 1 camel'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/taken-one', 'Asha took Gold'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/taken-one', 'Asha took Leather'],
  ['cards/taken-one', 'Belen took Cloth'],
  ['cards/sold', 'Asha sold 1 Leather · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Cloth · earned 1 token'],
  ['cards/taken-camels', 'Asha took all 1 camel'],
  ['cards/taken-camels', 'Belen took all 1 camel'],
  ['cards/taken-one', 'Asha took Silver'],
  ['cards/taken-one', 'Belen took Diamond'],
  ['cards/sold', 'Asha sold 2 Silver · earned 2 tokens'],
  ['cards/sold', 'Belen sold 2 Diamond · earned 1 token'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/taken-one', 'Belen took Spice'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Belen sold 1 Spice · earned 1 token'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/taken-one', 'Belen took Silver'],
  ['cards/sold', 'Asha sold 1 Spice · earned 1 token'],
  ['cards/sold', 'Belen sold 2 Silver · earned 2 tokens'],
  ['cards/taken-one', 'Asha took Silver'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/taken-one', 'Asha took Spice'],
  ['cards/sold', 'Belen sold 1 Leather · earned 1 token'],
  ['cards/taken-one', 'Asha took Cloth'],
  ['cards/taken-one', 'Belen took Leather'],
  ['cards/sold', 'Asha sold 1 Cloth · earned 1 token · Belen won round 3 and the match']
] as const satisfies readonly ExpectedGameLogEntry[];
